/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.0/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    // java
    `java-library`

    // Apply the application plugin to add support for building an application
    // application
}

repositories {
    mavenLocal()
    mavenCentral()

    // Use jcenter for resolving your dependenes.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // TODO

    api("org.xmlresolver", "xmlresolver", "0.14.0")
    api("net.sf.saxon", "Saxon-HE", "9.8.0-14")

    // Use TestNG framework, also requires calling test.useTestNG() below
    testImplementation("org.testng:testng:6.14.3")
}

// https://stackoverflow.com/questions/41794914/how-to-create-the-fat-jar-with-gradle-kotlin-script
val jingTrang = task("jingtrang", Jar::class) {
    from(listOf("build/jing.jar", "build/trang.jar").map { it -> zipTree(it) })
    with(tasks.jar.get() as CopySpec)
}

ant.importBuild("build.xml")
defaultTasks("ant-clean", "ant-jar", "jingtrang")

// if jing-trang is a composite, merged jar resolution
// does not work, even if the artifact is declared like below
artifacts {
    add("archives", jingTrang)
    add("default", jingTrang)
}

tasks {

    build {
        dependsOn("ant-clean", "ant-jar", "jingtrang")
    }

}
