= jing-trang
:groupId: org.relaxng
:artifactId: jing
:repository: jing-trang

image:https://img.shields.io/github/workflow/status/relaxng/{repository}/tests/master?style=plastic["Build Status", link="https://github.com/relaxng/jing-trang/actions/workflows/tests.yml?query=branch%3Amaster"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Artifact on Maven Central", link="http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22{groupId}%22%20a%3A%22{artifactId}%22"]
image:http://www.javadoc.io/badge/{groupId}/{artifactId}.svg["Javadocs", link="http://www.javadoc.io/doc/{groupId}/{artifactId}"]

== Building

. Ensure you have git and JDK 8 or above installed.
   All other dependencies are included in the repository.

. Set the `JAVA_HOME` environment variable to point to the directory
   where the JDK is installed. For example:

   * `export JAVA_HOME=/usr/lib/jvm/openjdk-11`    <- Ubuntu, etc.
   * `export JAVA_HOME=$(/usr/libexec/java_home)`  <- macOS
   * `set JAVA_HOME=C:\Program Files\Java\jdk-11`  <- Windows

. Clone the repository

    git clone https://github.com/relaxng/jing-trang.git`

. Change your working directory to be the `jing-trang` directory (that is,
   the directory containing this file).

. Run `./gradlew` (Linux, macOS) or `.\gradle.bat` (Windows) at the root of the repository to build the project.
   When the build completes, you should find `jing.jar` and `trang.jar` files
   in the `build` subdirectory.
   You can also use `./gradlew test` or `.\gradle.bat test` to run the `test` target, which
   will build the jars and then run some tests.
